---
title       : Elastic R API
subtitle    : Data Science Team Weekly Sync
author      : Summit Suen
job         : Etu
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Install 

```{r, eval=FALSE}
## Install from CRAN
install.packages("devtools")
## Or install development version:
devtools::install_github("ropensci/elastic")
```

---

## Connect

```{r}
library('elastic')
load("es.RData")
connect(es_base = base, es_port = port)
# default base = "http://127.0.0.1" and default port = 9200
```

---

## Get Data

- Sample data provided by elastic package, use bulk api to put json file into elasticsearch

```{r}
shakespeare <- system.file("examples", "shakespeare_data.json", package = "elastic")
aliases_get()
index_delete(index = "shakespeare")
aliases_get()
docs_bulk(shakespeare)
aliases_get()
```

---

## Search

```{r}
out <- Search(index="shakespeare")
out$hits$total
```

---

## Query

```{r}
out <- Search(index="shakespeare", type="act", q="speaker:KING HENRY IV")
out$hits[[1]]
out$hits$total
```

---

## Query

- Query DSL searches - queries sent in the body of the request

```{r}
aggs <- '{"aggs":{"stats":{"terms":{"field":"text_entry"}}}}'
out <- Search(index="shakespeare", body=aggs)
out$hits$hits[[1]]$`_source`$speaker
out$hits$hits[[1]]$`_source`$text_entry
```

